version: 2
jobs:
  build:
    working_directory: ~/code

    docker:
      - image: circleci/android:api-27-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Clean
          command: ./gradlew clean

      - run:
          name: Build
          command: ./gradlew build
                   -Dorg.gradle.daemon=true
                   -Dorg.gradle.parallel=true
                   -Dorg.gradle.configureondemand=true
                   -Dorg.gradle.caching=false
                   -Dorg.gradle.jvmargs=-Xmx3g
                   -Dandroid.enableAapt2=true
                   -Dorg.gradle.warning.mode=all
                   -Dandroid.enableD8=true

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: apks/debug/app-debug.apk

      - store_artifacts:
          path: app/build/outputs/apk/debug/mapping.txt
          destination: apks/debug/mapping.txt

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: apks/release/app-release.apk

      - store_artifacts:
          path: app/build/outputs/apk/release/mapping.txt
          destination: apks/release/mapping.txt

      - store_test_results:
          path: app/build/test-results
